dist: bionic
language: csharp
solution: AutoMapper.Contrib.Autofac.DependencyInjection.sln
mono: none
dotnet: 5.0.202

addons:
  apt:
    update: true

stages:
  - build
  - test
  - publish

jobs:
  include:
    - stage: build
      name: dotnet build
      script: dotnet build
    - stage: test
      name: dotnet test
      before_script:
        - sudo apt-get update && sudo apt-get install curl -y
      script: ./test.sh
    - stage: publish
      name: publish-packages
      if: tag IS present
      script: ./publish-packages.sh "$NUGET_SOURCE" "$CLEANCODELABS_NUGET_KEY" "$TRAVIS_TAG"

