on: push
name: Build Application
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json
    
    - name: Build solution
      run: dotnet build -c Release

    - name: Test solution and upload code coverage
      run: |
        chmod +x test.sh
        ./test.sh
