on:
  push:
    tags:
      - '*'
name: Release package
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Publish package
      run: |
        export TAG=${{github.ref_name}}
        export NUGET_API_URL=https://api.nuget.org/v3/index.json
        export NUGET_KEY=${{secrets.NUGET_KEY}}
        chmod +x ./publish-packages.sh
        ./publish-packages.sh
